### ISSUE TITLE
10 intermediate-level scenario-based troubleshooting questions focused on the Kubernetes namespace topic

### ISSUE THREAD

**Issue by ankitiitians** [ankitiitians/monitoring-and-validating-a-Cerner-Millennium-environment#2]
Below is a list of 10 intermediate-level scenario-based troubleshooting questions focused on the Kubernetes namespace topic, tailored for a DevOps Engineer 2 interview. These questions are designed to test practical knowledge of namespaces, resource management, and debugging at an intermediate level, assuming familiarity with Kubernetes basics but not requiring advanced expertise. Each question includes troubleshooting steps and solutions, complementing the previous set of scenarios.

---

### 1. Scenario: Pods in a Namespace Are Not Using the Correct Service Account
**Question**: A team reports that pods in the `app` namespace are failing to access a restricted API due to authentication errors. You suspect the pods are not using the intended service account. How would you troubleshoot and resolve this?

**Troubleshooting Steps**:
1. **Check Pod Service Account**:
   - Inspect the pod’s service account: `kubectl get pods -n app -o yaml | grep serviceAccount`
   - Verify if the correct service account is assigned.
2. **Verify Service Account Existence**:
   - List service accounts in the namespace: `kubectl get serviceaccount -n app`
   - Ensure the intended service account exists.
3. **Check RBAC Bindings**:
   - Verify if the service account has the necessary permissions: `kubectl get rolebindings,clusterrolebindings -n app`
   - Run: `kubectl describe rolebinding <rolebinding-name> -n app`
4. **Inspect Pod Logs**:
   - Check pod logs for authentication errors: `kubectl logs <pod-name> -n app`

**Solution**:
- If the pod is using the default service account, update the pod spec to use the correct one:
  ```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: app-pod
    namespace: app
  spec:
    serviceAccountName: custom-sa
  ```
- Create the service account if it doesn’t exist:
  ```bash
  kubectl create serviceaccount custom-sa -n app
  ```
- Bind the service account to a role with the required permissions:
  ```yaml
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: custom-sa-binding
    namespace: app
  subjects:
  - kind: ServiceAccount
    name: custom-sa
    namespace: app
  roleRef:
    kind: Role
    name: api-access
    apiGroup: rbac.authorization.k8s.io
  ```
- Restart the pod to apply changes: `kubectl delete pod <pod-name> -n app && kubectl apply -f pod.yaml`

---

### 2. Scenario: Namespace Has Too Many Pods Running
**Question**: A namespace `staging` is hitting the pod count limit defined in its `ResourceQuota`, causing new deployments to fail. How would you troubleshoot and address this issue?

**Troubleshooting Steps**:
1. **Check Resource Quota**:
   - View the quota: `kubectl get resourcequota -n staging`
   - Inspect usage: `kubectl describe resourcequota -n staging`
2. **List Pods**:
   - Check the number of pods: `kubectl get pods -n staging | wc -l`
   - Identify pods by deployment or workload: `kubectl get deployments,statefulsets -n staging`
3. **Analyze Pod Necessity**:
   - Determine if all pods are necessary or if some can be scaled down.
   - Check for orphaned pods: `kubectl get pods -n staging --show-labels`
4. **Check Events**:
   - Look for quota-related errors: `kubectl get events -n staging`

**Solution**:
- Scale down unnecessary deployments:
  ```bash
  kubectl scale deployment <deployment-name> --replicas=2 -n staging
  ```
- Delete orphaned or unused pods:
  ```bash
  kubectl delete pod <pod-name> -n staging
  ```
- If the pod limit is too restrictive, update the `ResourceQuota`:
  ```yaml
  apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: staging-quota
    namespace: staging
  spec:
    hard:
      pods: "50"
  ```
- Apply the updated quota: `kubectl apply -f quota.yaml`

---

### 3. Scenario: Cross-Namespace Service Discovery Failure
**Question**: An application in the `frontend` namespace cannot resolve a service in the `backend` namespace, resulting in a "service not found" error. How would you troubleshoot and resolve this?

**Troubleshooting Steps**:
1. **Verify Service Existence**:
   - Check if the service exists: `kubectl get svc -n backend`
   - Confirm the service has an endpoint: `kubectl describe svc <service-name> -n backend`
2. **Test DNS Resolution**:
   - Exec into a pod in the `frontend` namespace: `kubectl exec -n frontend <pod-name> -- nslookup <service-name>.backend.svc.cluster.local`
   - Check if DNS resolves correctly.
3. **Inspect Network Policies**:
   - Verify if a `NetworkPolicy` in `backend` restricts access: `kubectl get networkpolicy -n backend`
4. **Check CoreDNS**:
   - Inspect CoreDNS logs for errors: `kubectl logs -n kube-system -l k8s-app=kube-dns`

**Solution**:
- Ensure the application uses the fully qualified DNS name: `<service-name>.backend.svc.cluster.local`.
- If a `NetworkPolicy` blocks access, update it to allow traffic from `frontend`:
  ```yaml
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-frontend
    namespace: backend
  spec:
    podSelector:
      matchLabels:
        app: backend
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: frontend
  ```
- If DNS resolution fails, restart CoreDNS pods: `kubectl delete pod -n kube-system -l k8s-app=kube-dns`

---

### 4. Scenario: Namespace Missing Expected Labels
**Question**: A CI/CD pipeline fails to deploy resources to the `test` namespace because it lacks expected labels for a monitoring tool. How would you troubleshoot and fix this?

**Troubleshooting Steps**:
1. **Check Namespace Labels**:
   - View namespace metadata: `kubectl get ns test -o yaml`
   - Confirm if the required labels (e.g., `monitor: enabled`) are present.
2. **Verify Pipeline Configuration**:
   - Check the pipeline to identify the expected labels.
3. **Inspect Monitoring Tool**:
   - If using a tool like Prometheus, check its service discovery configuration for namespace label selectors.
4. **Check Events**:
   - Look for related errors: `kubectl get events -n test`

**Solution**:
- Add the missing labels to the namespace:
  ```bash
  kubectl label namespace test monitor=enabled
  ```
- Verify the labels: `kubectl get ns test --show-labels`
- Update the pipeline to apply labels during namespace creation:
  ```yaml
  apiVersion: v1
  kind: Namespace
  metadata:
    name: test
    labels:
      monitor: enabled
  ```
- Apply the updated namespace: `kubectl apply -f namespace.yaml`

---

### 5. Scenario: Namespace-Specific ConfigMap Not Applied
**Question**: A pod in the `dev` namespace is not picking up the expected configuration from a ConfigMap, causing application errors. How would you troubleshoot and resolve this?

**Troubleshooting Steps**:
1. **Verify ConfigMap Existence**:
   - Check if the ConfigMap exists: `kubectl get configmap -n dev`
   - Inspect its contents: `kubectl describe configmap <configmap-name> -n dev`
2. **Check Pod Configuration**:
   - Verify the pod references the ConfigMap: `kubectl get pod <pod-name> -n dev -o yaml | grep configMap`
3. **Inspect Pod Logs**:
   - Check for errors related to configuration: `kubectl logs <pod-name> -n dev`
4. **Validate Mount Path**:
   - Ensure the ConfigMap is mounted correctly in the pod spec.

**Solution**:
- Create or update the ConfigMap:
  ```yaml
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: app-config
    namespace: dev
  data:
    key: value
  ```
- Update the pod to use the ConfigMap:
  ```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: app-pod
    namespace: dev
  spec:
    containers:
    - name: app
      image: app-image
      env:
      - name: CONFIG_KEY
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: key
  ```
- Restart the pod: `kubectl delete pod <pod-name> -n dev && kubectl apply -f pod.yaml`

---

### 6. Scenario: Namespace-Level Storage Issues
**Question**: Pods in the `data` namespace fail to start with an error: "PersistentVolumeClaim not found." How would you troubleshoot and resolve this?

**Troubleshooting Steps**:
1. **Check PVCs**:
   - List PVCs in the namespace: `kubectl get pvc -n data`
   - Verify if the referenced PVC exists: `kubectl describe pod <pod-name> -n data`
2. **Inspect StorageClass**:
   - Check if the PVC references a valid `StorageClass`: `kubectl get storageclass`
3. **Check Events**:
   - Look for PVC binding errors: `kubectl get events -n data`
4. **Verify Pod Spec**:
   - Ensure the pod references the correct PVC: `kubectl get pod <pod-name> -n data -o yaml`

**Solution**:
- Create the missing PVC:
  ```yaml
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: data-pvc
    namespace: data
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  ```
- Apply the PVC: `kubectl apply -f pvc.yaml`
- Update the pod to use the PVC:
  ```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: data-pod
    namespace: data
  spec:
    containers:
    - name: app
      image: app-image
      volumeMounts:
      - mountPath: /data
        name: data-volume
    volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: data-pvc
  ```
- Restart the pod: `kubectl apply -f pod.yaml`

---

### 7. Scenario: Namespace-Specific Ingress Not Working
**Question**: An Ingress resource in the `web` namespace is not routing traffic to the correct service, returning a 404 error. How would you troubleshoot and resolve this?

**Troubleshooting Steps**:
1. **Check Ingress Configuration**:
   - View the Ingress resource: `kubectl get ingress -n web`
   - Inspect rules: `kubectl describe ingress <ingress-name> -n web`
2. **Verify Service**:
   - Ensure the service exists and matches the Ingress backend: `kubectl get svc -n web`
3. **Check Ingress Controller**:
   - Verify the Ingress controller logs (e.g., NGINX, Traefik): `kubectl logs -n <controller-namespace> <controller-pod>`
4. **Test DNS**:
   - Confirm the Ingress hostname resolves correctly: `nslookup <ingress-hostname>`

**Solution**:
- Update the Ingress to point to the correct service:
  ```yaml
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: web-ingress
    namespace: web
  spec:
    rules:
    - host: app.example.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: web-service
              port:
                number: 80
  ```
- Verify the service selector matches the pod labels:
  ```yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: web-service
    namespace: web
  spec:
    selector:
      app: web
    ports:
    - port: 80
      targetPort: 8080
  ```
- Restart the Ingress controller if needed: `kubectl rollout restart deployment <controller-name> -n <controller-namespace>`

---

### 8. Scenario: Namespace Isolation Causing Application Issues
**Question**: Applications in the `isolated` namespace cannot communicate with other namespaces due to strict isolation. How would you troubleshoot and relax the isolation?

**Troubleshooting Steps**:
1. **Check Network Policies**:
   - List network policies: `kubectl get networkpolicy -n isolated`
   - Inspect rules: `kubectl describe networkpolicy <policy-name> -n isolated`
2. **Verify Namespace Labels**:
   - Check namespace labels: `kubectl get ns isolated -o yaml`
   - Ensure labels align with network policy selectors.
3. **Test Connectivity**:
   - Exec into a pod and test connectivity: `kubectl exec -n isolated <pod-name> -- curl <service>.other-ns.svc.cluster.local`
4. **Check CNI Plugin**:
   - Verify the CNI plugin (e.g., Calico) configuration for namespace isolation.

**Solution**:
- Update the `NetworkPolicy` to allow specific traffic:
  ```yaml
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-specific-ns
    namespace: isolated
  spec:
    podSelector: {}
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: other-ns
  ```
- Apply the policy: `kubectl apply -f networkpolicy.yaml`
- If isolation is unnecessary, remove the restrictive policy: `kubectl delete networkpolicy <policy-name> -n isolated`

---

### 9. Scenario: Namespace Resource Cleanup
**Question**: A namespace `temp` contains old, unused resources (pods, configmaps, etc.) that are consuming resources. How would you troubleshoot and clean up the namespace?

**Troubleshooting Steps**:
1. **List Resources**:
   - Check all resources: `kubectl get all -n temp`
   - Include other resource types: `kubectl get configmap,secret,pvc -n temp`
2. **Check Resource Usage**:
   - Use `kubectl top pods -n temp` to identify resource consumption.
3. **Verify Resource Ownership**:
   - Check if resources belong to active workloads: `kubectl get deployments,statefulsets -n temp`
4. **Inspect Labels**:
   - Look for labels to identify unused resources: `kubectl get pods -n temp --show-labels`

**Solution**:
- Delete unused resources:
  ```bash
  kubectl delete pod,configmap,secret --all -n temp
  ```
- If specific resources are identified as unused, delete them selectively:
  ```bash
  kubectl delete pod <pod-name> -n temp
  ```
- Automate cleanup with a script:
  ```bash
  for resource in $(kubectl get pod -n temp -o name -l app=unused); do
    kubectl delete $resource -n temp
  done
  ```
- Consider adding a `ResourceQuota` to prevent future over-provisioning.

---

### 10. Scenario: Namespace-Specific Logging Issues
**Question**: Logs from pods in the `logging` namespace are not being collected by the cluster’s logging solution (e.g., Fluentd). How would you troubleshoot and resolve this?

**Troubleshooting Steps**:
1. **Check Pod Labels**:
   - Verify if pods have the correct labels for the logging agent: `kubectl get pods -n logging --show-labels`
2. **Inspect Logging Agent**:
   - Check the logging agent’s configuration (e.g., Fluentd, Filebeat): `kubectl get daemonset -n <logging-namespace>`
   - View logs: `kubectl logs -n <logging-namespace> <logging-pod>`
3. **Verify Namespace Scope**:
   - Ensure the logging agent is configured to collect logs from the `logging` namespace.
4. **Check RBAC**:
   - Verify the logging agent’s service account has permissions: `kubectl get rolebindings -n logging`

**Solution**:
- Add required labels to pods:
  ```bash
  kubectl label pod <pod-name> -n logging app=loggable
  ```
- Update the logging agent’s configuration to include the `logging` namespace:
  ```yaml
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: fluentd-config
    namespace: logging-system
  data:
    fluentd.conf: |
      <source>
        @type kubernetes
        namespaces ["logging"]
      </source>
  ```
- Ensure the logging agent’s service account has permissions:
  ```yaml
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: logging-access
    namespace: logging
  subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: logging-system
  roleRef:
    kind: Role
    name: pod-reader
    apiGroup: rbac.authorization.k8s.io
  ```
- Restart the logging agent: `kubectl rollout restart daemonset <logging-daemonset> -n logging-system`

---

### Key Notes for Interview Preparation
- **Intermediate Focus**: These questions test practical troubleshooting skills, requiring familiarity with `kubectl` commands, YAML configurations, and common Kubernetes components (e.g., RBAC, NetworkPolicy, ConfigMaps).
- **Practical Debugging**: Emphasize step-by-step debugging with commands like `kubectl describe`, `kubectl logs`, and `kubectl exec`.
- **Namespace Awareness**: Highlight the importance of namespace scoping for resources, policies, and access control.
- **Automation and Cleanup**: Show awareness of scripting and cleanup strategies to manage namespaces efficiently.
- **Tooling**: Reference common tools (e.g., Fluentd, Prometheus) to demonstrate real-world applicability.

These 10 questions complement the previous set by focusing on intermediate-level scenarios that are likely to arise in a DevOps Engineer 2 interview. They test practical skills in debugging namespace-related issues while avoiding overly complex edge cases. If you need more specific scenarios, deeper explanations, or additional topics, let me know!
